// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwieWE1-fhd3GxTsIZ3SYkBn2dfb12apE',
    appId: '1:960211748522:web:78ba7a952b531d9dbe72d3',
    messagingSenderId: '960211748522',
    projectId: 'childsafety-466d3',
    authDomain: 'childsafety-466d3.firebaseapp.com',
    storageBucket: 'childsafety-466d3.firebasestorage.app',
    measurementId: 'G-BGDK0H6Q09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbJ0U7Vt3HUgUVIjUXq72dAWkc9De9O6k',
    appId: '1:960211748522:android:4c305629c9272423be72d3',
    messagingSenderId: '960211748522',
    projectId: 'childsafety-466d3',
    storageBucket: 'childsafety-466d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGsUNQJx23SqQJGI7R2MaT3eQMJM59ZS4',
    appId: '1:960211748522:ios:dad9bde2207f9607be72d3',
    messagingSenderId: '960211748522',
    projectId: 'childsafety-466d3',
    storageBucket: 'childsafety-466d3.firebasestorage.app',
    iosBundleId: 'com.example.childSafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGsUNQJx23SqQJGI7R2MaT3eQMJM59ZS4',
    appId: '1:960211748522:ios:dad9bde2207f9607be72d3',
    messagingSenderId: '960211748522',
    projectId: 'childsafety-466d3',
    storageBucket: 'childsafety-466d3.firebasestorage.app',
    iosBundleId: 'com.example.childSafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwieWE1-fhd3GxTsIZ3SYkBn2dfb12apE',
    appId: '1:960211748522:web:fee4535c4bf5159fbe72d3',
    messagingSenderId: '960211748522',
    projectId: 'childsafety-466d3',
    authDomain: 'childsafety-466d3.firebaseapp.com',
    storageBucket: 'childsafety-466d3.firebasestorage.app',
    measurementId: 'G-N7YF18B25N',
  );
}
